import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/hooks/use-toast';
import { isValidUUID } from '@/lib/validation';
import { logActivity } from '@/lib/activityLogger';
import type { Json } from '@/integrations/supabase/types';

interface InvoiceItem {
  description: string;
  quantity: number;
  rate: number;
  amount: number;
}

export interface Invoice {
  id: string;
  user_id: string;
  invoice_number: string;
  client_id: string | null;
  project_id: string | null;
  items: InvoiceItem[];
  subtotal: number;
  discount: number;
  tax: number;
  total: number;
  status: string;
  is_deleted: boolean;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface InvoiceInput {
  client_id: string;
  project_id?: string;
  items: InvoiceItem[];
  discount?: number;
  tax?: number;
  status?: string;
}

// Helper to parse items from JSONB
const parseItems = (items: Json): InvoiceItem[] => {
  if (!items || !Array.isArray(items)) return [];
  return items.map(item => {
    if (typeof item === 'object' && item !== null && !Array.isArray(item)) {
      const obj = item as Record<string, Json>;
      return {
        description: String(obj.description || ''),
        quantity: Number(obj.quantity || 1),
        rate: Number(obj.rate || 0),
        amount: Number(obj.amount || 0)
      };
    }
    return { description: '', quantity: 1, rate: 0, amount: 0 };
  });
};

// Helper to convert items to JSON
const itemsToJson = (items: InvoiceItem[]): Json => {
  return items.map(item => ({
    description: item.description,
    quantity: item.quantity,
    rate: item.rate,
    amount: item.amount
  })) as Json;
};

export function useInvoices() {
  const { user, profile, isAdmin, isAuthenticated, refreshSession } = useAuth();
  const { toast } = useToast();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  // Fetch invoices (excluding deleted ones)
  const fetchInvoices = async () => {
    if (!user) return;

    try {
      setLoading(true);
      const { data, error: fetchError } = await supabase
        .from('invoices')
        .select('*')
        .eq('is_deleted', false)
        .order('created_at', { ascending: false });

      if (fetchError) throw fetchError;

      // Parse items from JSONB
      const parsedInvoices: Invoice[] = (data || []).map(inv => ({
        ...inv,
        items: parseItems(inv.items as Json)
      }));

      setInvoices(parsedInvoices);
      setError(null);
    } catch (err: any) {
      setError(err.message);
      console.error('Error fetching invoices:', err);
    } finally {
      setLoading(false);
    }
  };

  // Add new invoice - invoice_number is auto-generated by DB
  const addInvoice = async (input: InvoiceInput): Promise<boolean> => {
    if (!user) return false;

    // Validate client_id UUID
    if (!isValidUUID(input.client_id)) {
      toast({
        title: "ত্রুটি!",
        description: "ভুল ক্লায়েন্ট আইডি পাঠানো হয়েছে, অনুগ্রহ করে আবার নির্বাচন করুন।",
        variant: "destructive",
      });
      return false;
    }

    // Validate project_id UUID if provided
    if (input.project_id && !isValidUUID(input.project_id)) {
      toast({
        title: "ত্রুটি!",
        description: "ভুল প্রজেক্ট আইডি পাঠানো হয়েছে, অনুগ্রহ করে আবার নির্বাচন করুন।",
        variant: "destructive",
      });
      return false;
    }

    try {
      const subtotal = input.items.reduce((sum, item) => sum + item.amount, 0);
      const total = subtotal - (input.discount || 0) + (subtotal * (input.tax || 0) / 100);

      // Do NOT send invoice_number - it's auto-generated by DB default
      const { data: insertedData, error: insertError } = await supabase
        .from('invoices')
        .insert({
          user_id: user.id,
          client_id: input.client_id,
          project_id: input.project_id || null,
          items: itemsToJson(input.items),
          subtotal,
          discount: input.discount || 0,
          tax: input.tax || 0,
          total,
          status: input.status || 'বকেয়া',
          is_deleted: false,
        })
        .select('invoice_number')
        .single();

      if (insertError) throw insertError;

      const invoiceNumber = insertedData?.invoice_number || 'নতুন ইনভয়েস';

      toast({
        title: "সফল!",
        description: `ইনভয়েস ${invoiceNumber} সফলভাবে তৈরি হয়েছে`,
      });

      // Log activity
      await logActivity({
        userId: user.id,
        userName: profile?.name || 'অজানা ব্যবহারকারী',
        action: 'create',
        module: 'invoices',
        recordTitle: invoiceNumber,
        details: `নতুন ইনভয়েস তৈরি হয়েছে: ${invoiceNumber}`,
      });

      await fetchInvoices();
      return true;
    } catch (err: any) {
      console.error('Invoice creation error:', err);
      toast({
        title: "ত্রুটি!",
        description: err.message || "ইনভয়েস তৈরি করতে সমস্যা হয়েছে",
        variant: "destructive",
      });
      return false;
    }
  };

  // Update invoice
  const updateInvoice = async (invoiceId: string, input: Partial<InvoiceInput>): Promise<boolean> => {
    if (!user) return false;

    // Validate invoiceId UUID
    if (!isValidUUID(invoiceId)) {
      toast({
        title: "ত্রুটি!",
        description: "ভুল ইনভয়েস আইডি পাঠানো হয়েছে, অনুগ্রহ করে আবার নির্বাচন করুন।",
        variant: "destructive",
      });
      return false;
    }

    try {
      const updateData: Record<string, any> = {};
      
      if (input.client_id) updateData.client_id = input.client_id;
      if (input.project_id !== undefined) updateData.project_id = input.project_id || null;
      if (input.status) updateData.status = input.status;
      if (input.discount !== undefined) updateData.discount = input.discount;
      if (input.tax !== undefined) updateData.tax = input.tax;
      
      if (input.items) {
        updateData.items = itemsToJson(input.items);
        const subtotal = input.items.reduce((sum, item) => sum + item.amount, 0);
        const discount = input.discount ?? 0;
        const tax = input.tax ?? 0;
        updateData.subtotal = subtotal;
        updateData.total = subtotal - discount + (subtotal * tax / 100);
      }

      const { error: updateError } = await supabase
        .from('invoices')
        .update(updateData)
        .eq('id', invoiceId);

      if (updateError) throw updateError;

      toast({
        title: "সফল!",
        description: "সফলভাবে আপডেট হয়েছে",
      });

      await fetchInvoices();
      return true;
    } catch (err: any) {
      toast({
        title: "ত্রুটি!",
        description: err.message || "আপডেট করতে সমস্যা হয়েছে",
        variant: "destructive",
      });
      return false;
    }
  };

  // Check if invoice can be deleted
  const canDeleteInvoice = async (invoiceId: string): Promise<{ canDelete: boolean; reason?: string }> => {
    // Validate invoiceId UUID
    if (!isValidUUID(invoiceId)) {
      return { canDelete: false, reason: "ভুল আইডি পাঠানো হয়েছে" };
    }

    try {
      const { data: payments } = await supabase
        .from('payments')
        .select('id')
        .eq('invoice_id', invoiceId)
        .eq('is_deleted', false)
        .limit(1);

      if (payments && payments.length > 0) {
        return { canDelete: false, reason: "এই ইনভয়েসের সাথে পেমেন্ট যুক্ত আছে, তাই ডিলিট করা যাবে না।" };
      }

      return { canDelete: true };
    } catch (err) {
      return { canDelete: false, reason: "যাচাই করতে সমস্যা হয়েছে" };
    }
  };

  // Hard delete invoice (admin only)
  const deleteInvoice = async (invoiceId: string): Promise<boolean> => {
    // Check authentication first
    if (!isAuthenticated() || !user) {
      toast({
        title: "সেশন শেষ!",
        description: "অনুগ্রহ করে আবার লগইন করুন",
        variant: "destructive",
      });
      navigate('/auth');
      return false;
    }

    // Validate invoiceId UUID
    if (!isValidUUID(invoiceId)) {
      toast({
        title: "ত্রুটি!",
        description: "ভুল ইনভয়েস আইডি পাঠানো হয়েছে, অনুগ্রহ করে আবার নির্বাচন করুন।",
        variant: "destructive",
      });
      return false;
    }

    try {
      // Refresh session to ensure valid token
      const refreshedSession = await refreshSession();
      if (!refreshedSession) {
        toast({
          title: "সেশন শেষ!",
          description: "অনুগ্রহ করে আবার লগইন করুন",
          variant: "destructive",
        });
        navigate('/auth');
        return false;
      }

      // Check admin status directly from database
      const { data: roleData, error: roleError } = await supabase
        .from('user_roles')
        .select('role')
        .eq('user_id', user.id)
        .eq('role', 'admin')
        .maybeSingle();

      if (roleError) {
        console.error('Role check error:', roleError);
      }

      if (!roleData) {
        toast({
          title: "অনুমতি নেই!",
          description: "শুধুমাত্র অ্যাডমিন ইনভয়েস মুছতে পারেন",
          variant: "destructive",
        });
        return false;
      }

      const invoice = invoices.find(i => i.id === invoiceId);
      
      // Hard delete - permanently remove from database
      const { error: deleteError } = await supabase
        .from('invoices')
        .delete()
        .eq('id', invoiceId);

      if (deleteError) {
        console.error('Invoice delete error details:', {
          code: deleteError.code,
          message: deleteError.message,
          details: deleteError.details,
          hint: deleteError.hint
        });
        throw deleteError;
      }

      // Log activity
      await logActivity({
        userId: user.id,
        userName: profile?.name || 'অজানা ব্যবহারকারী',
        action: 'delete',
        module: 'invoices',
        recordId: invoiceId,
        recordTitle: invoice?.invoice_number,
        details: `ইনভয়েস স্থায়ীভাবে মুছে ফেলা হয়েছে: ${invoice?.invoice_number || 'অজানা'}`,
      });

      // Refetch list after success
      await fetchInvoices();

      toast({
        title: "সফলভাবে মুছে ফেলা হয়েছে",
        description: "ইনভয়েস স্থায়ীভাবে মুছে ফেলা হয়েছে",
      });

      return true;
    } catch (err: any) {
      console.error('Invoice delete error:', err);
      
      if (err.code === '42501' || err.message?.includes('row-level security')) {
        toast({
          title: "RLS ত্রুটি!",
          description: `ডাটাবেজ অনুমতি সমস্যা: ${err.message}`,
          variant: "destructive",
        });
      } else {
        toast({
          title: "ত্রুটি!",
          description: err.message || "মুছে ফেলতে সমস্যা হয়েছে",
          variant: "destructive",
        });
      }
      return false;
    }
  };

  // Get invoices by client
  const getInvoicesByClient = (clientId: string) => {
    return invoices.filter(i => i.client_id === clientId);
  };

  useEffect(() => {
    fetchInvoices();
  }, [user]);

  return {
    invoices,
    loading,
    error,
    fetchInvoices,
    addInvoice,
    updateInvoice,
    canDeleteInvoice,
    deleteInvoice,
    getInvoicesByClient,
  };
}
